

services:
  banking:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8080
      - MONGODB_URI=mongodb://host.docker.internal:27017
    networks:
      - shared-network

networks:
  shared-network:
    external: true
